### ISSUE TITLE
FT01 US01 - Bloquear o perfil de outro usuário

### ISSUE THREAD

**Issue by Rdlenke** [UnbFeelings/unb-feelings-web-app#65]
Eu, como usuário, desejo bloquear perfil de um outro usuário para evitar receber mensagens indesejadas de um usuário em específico.

**Critérios de aceitação**

- [ ] Um usuário deve ser capaz de bloquear um perfil de um outro usuário em um apoio feito por um usuário
- [ ] Deve existir uma confirmação para bloqueio de usuários.
- [ ] Dado um usuário X que bloqueou um usuário Y:
  - [ ] O usuário X não deve ser capaz de acessar informações referentes ao usuário Y;
  - [ ] O usuário Y não deve ser capaz de acessar informações referentes ao usuário X.
