### ISSUE TITLE
FT02 US02 - Desbloquear um usuário anteriormente bloqueado

### ISSUE THREAD

**Issue by Rdlenke** [UnbFeelings/unb-feelings-web-app#67]
Eu, como usuário, desejo desbloquear um usuário que foi bloqueado anteriormente para retomar a interação com ele.

**Critérios de aceitação**

- [ ] O usuário deve ser capaz de desbloquear um usuário.
- [ ] O usuário deve ser alertado do desbloqueio de outro usuário.
- [ ] Dado um usuário X que desbloqueou um usuário Y:
  - [ ] O usuário X deve ser capaz de acessar informações referentes ao usuário Y;
  - [ ] O usuário Y deve ser capaz de acessar informações referentes ao usuário X.
